export const AUTH_CONSTANTS = {
  VERIFICATION: {
    CODE_LENGTH: 6,
    EXPIRES_MINUTES: 10,
  },
  PASSWORD_RESET: {
    EXPIRES_MINUTES: 10,
  },
  LOGIN_TWO_FACTOR: {
    EXPIRES_MINUTES: 10,
  },
  SECURITY: {
    BCRYPT_SALT_ROUNDS: 10,
  },
};
